### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/user_guide#437]
Maybe an issue with the Sphinx version?

https://github.com/common-workflow-language/user_guide/actions/runs/6853168447/job/18633391061#step:10:23

```
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/runner/work/user_guide/user_guide/src/conf.py", line 257, in <module>
    from myst_parser.mdit_to_docutils.sphinx_ import SphinxRenderer, create_warning
ImportError: cannot import name 'create_warning' from 'myst_parser.mdit_to_docutils.sphinx_' (/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/myst_parser/mdit_to_docutils/sphinx_.py)
```

**Comment by mr-c** [comment]
Fixed!
